### ISSUE TITLE
Make the camera preview a fixed resolution

### ISSUE THREAD

**Issue by jonnyawsom3** [Yellow-Dog-Man/Resonite-Issues#1568]
### Is your feature request related to a problem? Please describe.

When increasing the resolution of the camera, the game is constantly rendered at up to 8K for a display only a few inches large in most cases.

### Describe the solution you'd like

The set resolution only needs to be rendered for a single frame to take the image, so a much lower resolution could be used for preview until the button is pressed, freeing up large amount of GPU performance.
When the 'Selfie projection' is enabled, the preview resolution could be increased for the larger preview size (But still limited to less than 8K...)

### Describe alternatives you've considered

Lowering the camera resolution between photos or deleting and respawning the camera between photos to regain performance

### Additional Context

This may have fit under a Content Issue instead, but I'm unsure if changing resolutions dynamically and taking single frame high res snapshots is a flux problem or an engine problem

### Requesters

jonnyawsom3

**Comment by Banane9** [comment]
It is a content issue, the preview size is disconnected from the render size - at least with the regular camera component.

**Comment by jonnyawsom3** [comment]
Ah, I see. Thanks

**Comment by JackTheFoxOtter** [comment]
This is indeed an issue with the default Resonite Essentials camera.

There is ProtoFlux packed to the "Resolution Entry Flux" slot that calculates the render resolution to drive the displayed string on the UIX canvas, and also drives the resolution of the RenderTextureProvider. However, it incorrectly drives the render resolution instead of the preview resolution to the resolution of the RenderTextureProvider. Changing this to the preview resolution resolves this issue. I've fixed this in my version of the camera, it's a minor fix but this is my corrected ProtoFlux for reference:

![20240331174302_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/62c545a5-20dc-4aaf-93f4-f938972bb467)

**Comment by JackTheFoxOtter** [comment]
Actually, there is an issue with my "fix". This will be the desirable solution for using the camera to take pictures, however, it will NOT be the desirable solution for using the camera for streaming, as when streaming, the preview resolution is the output resolution. So there will have to be a way to differentiate that. Preferrably though, it would still use the preview resolution when rendering the preview for anyone but the owner of the camera when they are mirroring to their screen.

**Comment by JackTheFoxOtter** [comment]
I've adjusted the RenderTextureProvider's resolution based on wether there is a simulating user (and the simulating user is the local user) now. If it's true, the render resolution will be used, otherwise the preview resolution. I *think* this should work in all situations, but I might have overlooked some scenarios. Regardless this is how I've implemented it on my camera now.

![20240331202848_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/86341ecd-0d0c-448f-9715-0ef6c68d84b6)

**Comment by Krzeszny** [comment]
7 months later and this camera still lags the game immensely at 8k, sometimes crashes users when taking 8k photos, and messes with their display resolution in desktop mode. Content team, can we ever count on you?

(By the way, the physical power button has no function.)

**Comment by Frooxius** [comment]
@Krzeszny Please avoid comments like that. They add unnecessary toxicity and makes things harder for us.

It is fair to bring up that issue is still affecting people, but making this personal or attacking the people over it crosses a line. Things slip through cracks and happen especially when there are a lot of issues. 

If you believe this is of importance then up vote this issue and tell others affected to do as well. This one doesn't have that many on it, so it wouldn't rise in priority as much on that alone.

We also ask that any separate issues need to be made as separate issues here as well. This is focused on partuclar problem. If you want to make sure all other problems are addressed, make sure they are properly addressed.

But before you do, please read our submission guidelines: https://github.com/Yellow-Dog-Man/Resonite-Issues/blob/main/README.md

They endure we can be focused on solving problems here. I undestrand that issues are frustrating, but this is not the place to air out frustrations, but to focus on the problems themselves.

**Comment by JackTheFoxOtter** [comment]
@Krzeszny in the meantime until the content team gets a chance to look at this, you can use the ProtoFlux code I provided to resolve the issue manually for the time being. Resonite allows you to favorite custom streaming cameras! So you can customize it to your liking (for example to tweak the render resolution logic, as I've demonstrated above).

**Comment by kulzae** [comment]
Id also prefer not to see other previews (like how the streaming camera hides them) by default as it just adds rendering overhead all the time. theres only a few scenarios you really need to see the preview of other peoples cameras

**Comment by Krzeszny** [comment]
@Frooxius I guess I went one step too far with the word "ever". I apologize, this kind of attitude won't happen again. And thank you for taking the time to explain.

Also, happy birthday!

**Comment by jonnyawsom3** [comment]
With the splittening tomorrow, I thought it was about time I fixed my own camera. Here's the before and after when set to 8K.
<img width="639" height="30" alt="Image" src="https://github.com/user-attachments/assets/353c766d-0dc6-4b54-9142-d9aa96633a84" />
<img width="640" height="29" alt="Image" src="https://github.com/user-attachments/assets/eeccd917-38f3-41bd-9917-85ce301f4d72" />

**Comment by Baplar** [comment]
I've unfortunately encountered this issue yesterday when I hosted a Resonite tour for my VRChat friend group.

When showing off the features of the default cameras, one of my friends opened the settings and went "ooh, super high resolutions!" and clicked the highest one.
Most people in the session (included myself as host) crashed to desktop in the following seconds.

On other platforms, having the option to take high resolution pictures is pretty common, and generally does not have the pitfall of rendering a full-size preview on every game engine frame, so they really did not expect to cause any issues when selecting the option, somewhat understandably so.

I love that some custom cameras implement a workaround for this, and I will start using and recommending them.
But I believe that alleviating this issue on the default cameras in the Essentials folder would be really important to avoid accidentally crashing new players in their early game experience.

**Comment by jonnyawsom3** [comment]
I tinkered with the camera flux and had my own ideas to improve it. Along with the 'standard' default camera, there's also the two-sided camera.
It renders both views constantly, at the set capture resolution. The camera for the side you're not viewing could be disabled, and the preview resolution changed depending on distance. That would cut the GPU load by around 8x at a guesstimate

**Comment by Baplar** [comment]
After inspecting the camera’s flux, turns out removing a bit of flux in the "Resolution Entry Flux" slot is enough to make the resolution stay at 720p, while still taking pictures at the requested resolution.

<img width="1876" height="496" alt="Image" src="https://github.com/user-attachments/assets/a997fbdb-fa50-44b8-8bb1-739701bcd4c9" />

I confirm that it works with both the UI camera and the "physical" camera. Having the camera set at 8k barely drops my framerate, but it does take 8k pictures! Works with all camera modes (2D, stereo, 360, object). Even works when holding the camera vertically, the pictures are taken in 8k in portrait orientation.
