### ISSUE TITLE
SteamVR pause can cause rendering resolution to dramatically reduce

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#2337]
### Describe the bug?

Opening and closing the SteamVR dashboard has a chance to get the game stuck in the "paused" state rendering at minimum resolution until a game reset. 

### To Reproduce

The issue is super inconsistent, but the most reliable ways I've found to cause it is to have the SteamVR dashboard open while another user joins or opens an inspector, and close the dashboard before the game recovers from the lag spike. 

### Expected behavior

For the game to recognize that the dashboard has been closed and return to the set rendering resolution

### Screenshots

![ffe33b36530d46bbb594eeb528e82f09](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/7236e392-fb0f-4e04-b741-11449c9181a5)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/96fe056e-2719-4357-a25c-d7fa3a9e4710)

### Resonite Version Number

Beta 2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[BUFU - 2024.6.11.74 - 2024-06-15 01_31_54.log](https://github.com/user-attachments/files/15845849/BUFU.-.2024.6.11.74.-.2024-06-15.01_31_54.log)

### Additional Context

I know the screenshots aren't very good, but this is an issue that primarily happens in headset and isn't anywhere nearly as obvious on either desktop mirror.

**Comment by shiftyscales** [comment]
On duplicate issue #2483 - @Geenz had noted:
> This is going to be either a Unity or SteamVR bug. I'd say this will be more fixable after Sauce.

Marking this issue as blocked by #1401 - after which we can re-evaluate this issue and see if it is still a problem.

**Comment by TheBasementNerd** [comment]
I'd like to add on that this issue (for me at least, on Index) is caused by having the SteamVR dashboard open while a datamodel loading hitch happens and then closed before the hitch has stopped, causing Resonite to permanently run at the blurred resolution that it's set to when the SteamVR dashboard is open, until a restart of the game

**Comment by goaaats** [comment]
This happens because the SteamVR Unity plugin can sometimes miss events when the game is hitching.

The resolution is set to 0.5f in S[teamVR_Render.OnInputFocus()](https://github.com/ValveSoftware/steamvr_unity_plugin/blob/056c82369d78f253af8cefcae9b289efd69bd960/Assets/SteamVR/Scripts/SteamVR_Render.cs#L237-L262) as a response to the unfocus event, but when the unfocus event happens twice in a row - as a result of a dropped refocus event - the code stores the already reduced resolution as the current resolution, causing it to never go back to the original resolution once a focus event occurs.

This is ostensibly a bug in the SteamVR plugin, but it would be trivially fixed by tracking the focus state in SteamVR_Render and not storing the overridden resolution in the field for the actual resolution. The lost events are somewhat troubling but the code that gets events from the OpenVR native looks fine to me and it seems like this is just expected behavior from OpenVR if your app is unresponsive for multiple seconds.

**Comment by Redd56** [comment]
Well unless steamvr or unity themselves freeze. In the latter case i dont really know of anything that would cause unity to freeze without ourright crashing the renderer

**Comment by Frooxius** [comment]
Is this still an issue after splittening?

With the renderer being open source, this could also be looked into by anyone, but if the issue is gone, we can just close this.

**Comment by tabithamoon** [comment]
This is still an issue as of Beta 2026.6.4.1252, though it happens less often.
Is this behavior inherent to the current Unity version? VRChat doesn't change resolution at all when the dashboard is open, but they are on Unity 2022.

**Comment by Frooxius** [comment]
I don't know, I haven't investigated this issue. Can be SteamVR, Unity, some other component or mix of things.

**Comment by goaaats** [comment]
It's still an issue, but happens much less frequently now due to the decoupling. It only repros when the Unity renderer itself freezes (as Redd mentioned, large mesh uploads can still cause this, for example).

Seems to be a problem with how SteamVR processes events. Would you want to preserve this behavior in general and just fix the problem, or remove it altogether like other apps do?

https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2337#issuecomment-3025681468

**Comment by tabithamoon** [comment]
I'm about to open a PR for Renderite to remove the resolution switching logic. Most modern VR games do not switch resolution when the dashboard is opened so I think patching out this behavior would be the simplest and most effective fix (for example, the whole system doesn't even exist in OpenXR land)
I just need to test this and I'll make the PR once I've confirmed it worked.

**Comment by tabithamoon** [comment]
It looks like that code that was patched by the old mod is not where the resolution changing is happening 😔
I haven't narrowed it down yet, though it seems to be in Valve's Unity plugin and not SteamVR itself, as other OpenVR titles (for example Unreal Engine 4 games) don't have this behavior.

**Comment by Comptr-user** [comment]
@tabithamoon
Are you still planning on making a PR for the renderer?
Just wanted to know before I potentially tried to make my own pr.

**Comment by tabithamoon** [comment]
@Comptr-user Unfortunately I couldn't manage to patch it out completely, the dashboard is seemingly a separate state from normal overlays (say, an overlay from Desktop+), which is the only resolution switch I managed to patch out.
Feel free to take a crack at it and make a PR.
