### ISSUE TITLE
API instability; timing out on headlesses.

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#3590]
### Describe the bug?

Currently, it appears that some headlesses are having issues connecting to the Resonite API and timing out constantly, causing issues with users joining among other things.

### To Reproduce

run a headless, wait for it to time out

### Expected behavior

API to be more stable

### Resonite Version Number

Beta 2025.1.14.6

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

[3bd82dd7-422e-431f-a5bd-fcd6ce426b80 - 2025.1.14.6 - 2025-01-25 06_38_30.log](https://github.com/user-attachments/files/18545122/3bd82dd7-422e-431f-a5bd-fcd6ce426b80.-.2025.1.14.6.-.2025-01-25.06_38_30.log)

### Reporters

bredo

**Comment by Frooxius** [comment]
I'm looking into this, I see degradation on the server side as well.

**Comment by Frooxius** [comment]
I've pushed an update that should help things a bit, but there's something more going on I think, so I'm leaving this open.

**Comment by shiftyscales** [comment]
That does sound to be the same as what is reported in this issue yes, @Krzeszny. Last night my first attempt to join a headless session timed out, but it connected afterward on the second try alright.

**Comment by Krzeszny** [comment]
I've been having the same issue every time I join most headlessed for 3 weeks, and some of my friends have been also complaining about it. Examples:

```
06:07:24.308 (100 FPS)	NetworkInitStart
06:07:24.309 (100 FPS)	Network manager: FrooxEngine.LNL_Manager - priority: 0
06:07:24.309 (100 FPS)	Network manager: FrooxEngine.SteamNetworkManager - priority: -100
06:07:24.309 (100 FPS)	Network manager: FrooxEngine.TCP_Manager - priority: -1000
06:07:24.309 (100 FPS)	Connecting to: lnl-nat://aba6f27b-c51c-49ba-ac03-0bcc96cd97cc/S-U-h33tology:meditation
06:07:24.312 (100 FPS)	LNL Connection for Address: lnl-nat://aba6f27b-c51c-49ba-ac03-0bcc96cd97cc/S-U-h33tology:meditation, World  (Handle: 25. Focus: Background, State: Initializing, InitState: InitializingNetwork, FailState: None, FailReason: , IsDestroyed: False, IsAuthority: False, SyncTick: 1, StateVersion: 1, Time: 0, TimeSinceLastUpdate: 0,017108 on port 50012. LocalBindIP: 0.0.0.0
06:07:24.313 (100 FPS)	Punchthrough attempt for lnl-nat://aba6f27b-c51c-49ba-ac03-0bcc96cd97cc/S-U-h33tology:meditation: 0
06:07:25.317 (102 FPS)	Punchthrough attempt for lnl-nat://aba6f27b-c51c-49ba-ac03-0bcc96cd97cc/S-U-h33tology:meditation: 1
06:07:25.390 (102 FPS)	NETWORK RECEIVE UNCONNECTED: 95.217.33.19:27000, token: SERVER_GONE:s-u-h33tology:meditation, connection token: S-U-h33tology:meditation
06:07:25.390 (102 FPS)	Connection to lnl-nat://aba6f27b-c51c-49ba-ac03-0bcc96cd97cc/S-U-h33tology:meditation failed: World.Error.SessionEnded
06:07:25.390 (102 FPS)	All protocols failed to establish connection
```
```
06:10:50.175 (100 FPS)	NetworkInitStart
06:10:50.175 (100 FPS)	Network manager: FrooxEngine.LNL_Manager - priority: 0
06:10:50.175 (100 FPS)	Network manager: FrooxEngine.SteamNetworkManager - priority: -100
06:10:50.175 (100 FPS)	Network manager: FrooxEngine.TCP_Manager - priority: -1000
06:10:50.175 (100 FPS)	Connecting to: lnl-nat://6a95325a-dbe2-4397-afda-f735285b5000/S-f2d8ffbb-6643-447c-876a-9f7745f3df50
06:10:50.176 (100 FPS)	LNL Connection for Address: lnl-nat://6a95325a-dbe2-4397-afda-f735285b5000/S-f2d8ffbb-6643-447c-876a-9f7745f3df50, World  (Handle: 30. Focus: Background, State: Initializing, InitState: InitializingNetwork, FailState: None, FailReason: , IsDestroyed: False, IsAuthority: False, SyncTick: 1, StateVersion: 1, Time: 0, TimeSinceLastUpdate: 0,0019852 on port 64407. LocalBindIP: 0.0.0.0
06:10:50.176 (100 FPS)	Punchthrough attempt for lnl-nat://6a95325a-dbe2-4397-afda-f735285b5000/S-f2d8ffbb-6643-447c-876a-9f7745f3df50: 0
06:10:50.368 (100 FPS)	NETWORK RECEIVE UNCONNECTED: 5.78.110.95:3000, token: SERVER_GONE:s-f2d8ffbb-6643-447c-876a-9f7745f3df50, connection token: S-f2d8ffbb-6643-447c-876a-9f7745f3df50
06:10:50.368 (100 FPS)	Connection to lnl-nat://6a95325a-dbe2-4397-afda-f735285b5000/S-f2d8ffbb-6643-447c-876a-9f7745f3df50 failed: World.Error.SessionEnded
06:10:50.368 (100 FPS)	All protocols failed to establish connection
```

**Comment by Krzeszny** [comment]
This bug is still present, where I have to keep spamming the join button, it doesn't work most of the time, and also session orbs are broken because of it. When I fail to establish connection on a session orb, clicking it more doesn't connect at all.

**Comment by Frooxius** [comment]
@Krzeszny Hmm, this actually seems to be a different issue entirely.

- From the log, that looks like error establishing connection to the host - where it appears the host is gone for some reason - this is separate from API servers
- It's not timing out on this end - the NAT node is saying that it doesn't know the server

Can you provide full logs for this please? I'll need them both from the client trying to connect and server that's hosting.

**Comment by JackTheFoxOtter** [comment]
I can confirm I've encountered those issues on my headless as well, actually since before MMC started. I usually have to press the "join" button 2 or 3 times before I actually establish a connection. During MMC most people of the team needed multiple attempts to join as well. The headless itself is hosted in a data center at Hetzner, so I highly doubt the issue is related to its internet connection.

I've just reproduced the issues on my headless for fresh logs.
1. Client joins headless - success
2. Client disconnects
3. Client joins headless - fails to establish connection
4. Client joins headless - success

Client Log:
[J4-C - 2025.3.11.1347 - 2025-03-15 12_00_41.log](https://github.com/user-attachments/files/19261073/J4-C.-.2025.3.11.1347.-.2025-03-15.12_00_41.log)

Headless Log:
[8ac022c8b4b7 - 2025.3.11.1347 - 2025-03-15 10_59_38.log](https://github.com/user-attachments/files/19261090/8ac022c8b4b7.-.2025.3.11.1347.-.2025-03-15.10_59_38.log)

**Comment by Krzeszny** [comment]
> Can you provide full logs for this please? I'll need them both from the client trying to connect and server that's hosting.

Not really, sorry Froox. I tried finding corresponding logs in my friend's hedless logs multiple times and there are no connection attempts from when I fail to connect. The headless just doesn't log it.

Below, after the second debug marker I failed to connect, and after the third debug marker I succeeded.
[DESKTOP-VHA2V7H - 2025.3.18.23 - 2025-03-18 08_05_17.log](https://github.com/user-attachments/files/19309620/DESKTOP-VHA2V7H.-.2025.3.18.23.-.2025-03-18.08_05_17.log)

**Comment by ProbablePrime** [comment]
I spoke to Froox about this yesterday. 

Jack's logs from a headless and a client are really helpful. I'm going to pair those up with the LNL Nat/Bridge node logs at that time. We can't share those logs but I'll see if there's anything there that might explain it.

Thank you!

**Comment by ProbablePrime** [comment]
Im seeing some un-healthyness in the Australian Bridge.

This might be an easy fix! :D

**Comment by ProbablePrime** [comment]
Alright, this is a lovely one! 

I think our original fixes did fix it elsewhere, but they introduced a subtle timing issue with the Bridges.

One of the fixes we did here to help with instability was to increase the interval at which Session Hosts report to our Bridges that they are available for NAT.

This was increased from 10 seconds to 15 seconds.

Now, over in bridge land, we have some code which will expire(delete) information stored on it about a Session Host if the Bridge doesn't get an update every 10 seconds. This is sometimes known as TTL, or lease time. But I'm bad with terminology words. Anyway,

So now the sequence of events for a new session that you host goes  like this(approximate timings shown):
- 0s -  Session Host says "Hi, I'm here you can punch me".
- 0-1s - Bridge stores that data
- 10s - Bridge deletes that data
- 15s - Session Host Says "Hi, I'm here you can punch me".
- 25s - Bridge deletes that data
- 30s - Session Host Says "Hi, I'm here you can punch me".
- Etc.

As you can see there's now a 5s gap periodically between LNL NAT Routes existing and not existing on the bridge.

If you try to connect during this 5s gap, you'll see a "Miss" (SERVER GONE, in the logs).

I am updating all Bridges to have:
1. A Config file driven expiry time
2. Updating that config value to match the new 15s from the client.

Once that's done if there are still some issues, I can up the bridge expiry time to say 16-20s to allow for "wiggle". 

However, if this "wiggle" time is too big then the same problem will occur but the other way around, as in the bridge says "hey yeah you can connect here" but you can't actually connect because the route has changed in the "wiggle" time. So I imagine leaving it at 15.

**Comment by ProbablePrime** [comment]
I've pulled some log lines from the past few hours that do show this too. This is a popular headless and its sequence of events matches what I said EXACTLY. Was very satisfying to go "OH HECK THE LOGS SHOW IT":

```
[00:29:10 INF SkyFrost.NetworkNode.Services.Bridge.BridgeService] SERVER REGISTERED: Key: s-u-REDACTED
[00:29:20 INF SkyFrost.NetworkNode.Services.Bridge.BridgeService] SERVER DEREGISTERED: Key: s-u-REDACTED
[00:29:25 INF SkyFrost.NetworkNode.Services.Bridge.BridgeService] SERVER REGISTERED: Key: s-u-REDACTED
[00:29:35 INF SkyFrost.NetworkNode.Services.Bridge.BridgeService] SERVER DEREGISTERED: Key: s-u-REDACTED
```

**Comment by ProbablePrime** [comment]
Deployed this fix to Australia(the one from the logs), the logs are much much happier now. 

I can't really paste them due to the need for redaction BUT Registrations and Expirations are both less frequent in the logs, which is a good thing! I'm also seeing a bunch of expirys that make more sense. For example a popular headless here responded perfectly for 10 minutes, missed 1 update and got expired and then immediately re-appeared with the next update. 

This is great too!

I will roll out to other nodes shortly.

**Comment by ProbablePrime** [comment]
I'm also going to in a subsequent update:
1. Move this to Docker for easier updates(I'm copying files right now >.<)
2. Add some metrics for the average amount of time we keep a registration in our records. 
    - In a perfect networking scenario, the amount of time we keep a registration in a bridge, should be close to the amount of time the session is open.
    - But we can alert on this changing too much. Like if a bunch of sessions start only persisting for 10s again we'll be able to see it.

**Comment by ProbablePrime** [comment]
I've rolled it out to the other nodes.

You can actually already see the improvement on some of the graphs:

![Image](https://github.com/user-attachments/assets/e9bbbdb6-91b3-46cb-9cdc-1d5f048a609e)

Pictured in Green is the Australia node(the first one I deployed). Ignore the magnitude of the graph but look at how smooth the line is AFTER the update compared to BEFORE.

**Comment by bredo228** [comment]
Haven't seen a connection failure since the update was pushed!

**Comment by ProbablePrime** [comment]
Alright, going to close this one out.

If there are other issues please make another issue. In that issue remember if possible to include the Headless and Client logs for situations like this. Replaying everything at the same time side by side in a split editor with the bridge, client and headless was the only way I figured this out this time :D.

**Comment by ProbablePrime** [comment]
Oh and for additional reference, all the bridges now operate on a 15.5 Second Expiry.

I added the 500ms to account for ping and wiggle.
