### ISSUE TITLE
Cursor Size becomes extremely large when laser is partially occluded by certain objects in VR

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [Yellow-Dog-Man/Resonite-Issues#3654]
### Describe the bug?

Due to some edge case (I don't know but prime theorized this a few? weeks ago in the discord) the cursor will become enlarged in VR if you are hovering over a far off object and your laser happens to intersect particular types of meshes. This can be distracting and would be good to fix as it happens in a few places every now and then to me and usually results in a few seconds of confusion, at least.

### To Reproduce

1. Spawn `resrec:///U-Venport/R-ae354234-cd8c-4d95-a606-f8479b5806ad` and any object (Lets say a cube for example)
    - Fyi, the tree is going to spawn in massive because I forgot to take into account scaling stuff when I saved it 
2. Place the cube far behind the tree you spawned in such a way that your laser could overlap the tree leaves
3. Point your laser at the cube without touching the leaves of the trees and then drag it towards them, your cursor will become giant when it overlaps them and stay that way until you are no longer

### Expected behavior

Cursors maintain a consistent size even in edge cases

### Screenshots

![Image](https://github.com/user-attachments/assets/4c2b7ca6-5b2b-4715-8699-ce1095f18247)

![Image](https://github.com/user-attachments/assets/33edea12-2b73-46eb-8d5f-3d842ea1e778)

a few examples

### Resonite Version Number

2025.2.4.1354

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[DESKTOP-GCR6JOJ - 2025.2.4.1354 - 2025-02-05 13_55_07.log](https://github.com/user-attachments/files/18678233/DESKTOP-GCR6JOJ.-.2025.2.4.1354.-.2025-02-05.13_55_07.log)

The log is longer than it needed to be but most of the information should be in the last 30 minutes or so since it didn't take me that long to test

### Additional Context

something something cheese

### Reporters

Venport/dustysprinkles

**Comment by shiftyscales** [comment]
Thanks for making this issue. Seeking input from @ProbablePrime as they were the ones to implement the new cursor scaling.

#3372 is another adjacent issue that covers situations in which cursor scaling is inconsistent.

**Comment by Redd56** [comment]
curses the issue was made

**Comment by GearBell** [comment]
This issue happens to me alot.
I have found avatars that scale and avatars with "detatched" laser locations (moved from native hand bone) cause this issue. One laser scales correctly with me, while the other maintains global 1 scale.

**Comment by Frooxius** [comment]
@ProbablePrime Would you be able to bump priority on this?

I've heard of users with photo-sensitivity being negatively affected by this due to causing sudden flickers in the community. I think that might warrant getting this resolved sooner.

**Comment by ProbablePrime** [comment]
@Frooxius Of course, probably Monday or Tuesday next week.

**Comment by Mhowser** [comment]
Here is a clip showing the problem 

https://github.com/user-attachments/assets/0f34f36f-bf65-4faa-91ed-ad046be5508b

**Comment by TisFoolish** [comment]
If you guys try to bisect the issue, I know that at least for me it started with the update that had Prime's changes to the cursor.

Also, it *looks* like it it's actually the secondary cursor that shows the direction is being reflected back towards the user

**Comment by Banane9** [comment]
> I've heard of users with photo-sensitivity being negatively affected by this due to causing sudden flickers in the community. I think that might warrant getting this resolved sooner.

Ah, based on that effect I referred to it as the flashbang cursor :'D

If it helps, I have fixed this in a mod before - basically just repeating the same code that the main cursor has for scaling for the direct cursor, rather than copying the scale.
The length of the indicator line also has to be adjusted.

https://github.com/ResoniteModdingGroup/CommunityBugFixCollection/blob/fix/flashbang-cursor/CommunityBugFixCollection/IndependentlyScaleDirectCursor.cs

**Comment by Banane9** [comment]
> Oh and I really like the documentation in: https://github.com/ResoniteModdingGroup/CommunityBugFixCollection
> 
> Thank you!

Happy if it helps. You're of course welcome to use any of the code in the fixes, although not all of it may be directly applicable to the regular source.

**Comment by ProbablePrime** [comment]
Coming soon!

**Comment by Frooxius** [comment]
Merged fix in 2025.3.25.1348! Thank you!

**Comment by Dusty-Sprinkles** [comment]
This still occurs, but less consistently as of Beta 2025.3.25.1348, https://go.resonite.com/record/U-WendigoWren/R-08169f1a-6156-495d-a006-1e1f2b8184da can replicate it in vr fairly easily, though its just for a frame

**Comment by Banane9** [comment]
@Dusty-Sprinkles you'd probably want to post a video / new log of it just for completeness 🤔

**Comment by Dusty-Sprinkles** [comment]
if noone else gets it by tomorrow I can do it but I'm done playing in vr for the night

**Comment by lxw404** [comment]
Here's some videos of this still happening in `Beta 2025.3.27.1177`:

https://github.com/user-attachments/assets/beab3676-659b-44fd-8e4e-2c132872e7de

https://github.com/user-attachments/assets/c7bf85d1-8062-4636-ade0-13a1f50d7071

It is easily reproduced with a big far away object that intersects with a close by object.

**Comment by Banane9** [comment]
Interesting, that seems like a worse version even where the direct cursor is the far-away scale while right at your face rather than at the in-between object (which also seemed to be happening still in the second video)

**Comment by Dusty-Sprinkles** [comment]
> Interesting, that seems like a worse version even where the direct cursor is the far-away scale while right at your face rather than at the in-between object (which also seemed to be happening still in the second video)

Thats about what is normal for it tbh, the examples I got in the start of the issue were honestly relatively tame, I've had screen covering cursor glitches before the first patch was applied in some worlds

**Comment by ProbablePrime** [comment]
Will take another look, apologies everyone :D

**Comment by ProbablePrime** [comment]
On a branch, i've added a setting to hide the "direct cursor" as its known.

I also reviewed all the code and the position and scale should be updated within the same method, so if one updates the other should.

I had an idea which was to move the scale adjustments to before the position.

So right now its:
1. Position It
2. Scale it

and after my change it is:
1. Scale It
2. Position It

I've also added that to the branch, however I'll need to reliably replicate the issue to test if my fix does anything.

Once again and for the community, I'd love a world orb/repro item that makes it easier to reproduce. I did try with the tree but I'm not able to.

@lxw404 What world was your original videos recorded in, the little structure there seems to be quite well qualified to reproduce this. Additionally have you modified your cursor or laser settings.

**Comment by Redd56** [comment]
for vr i know 2 ways to consistantly replicate this silly bug

**Comment by ProbablePrime** [comment]
I've tidied everything up just now, and yep we're fixed. 

Thank you everyone, this is now coming soon. And yes it includes a setting to completely turn off the direct cursors.

**Comment by ProbablePrime** [comment]
Locale strings here: https://github.com/Yellow-Dog-Man/Locale/pull/779

SO GLAD this is basically done now. :D
