### ISSUE TITLE
Dynamic bone player collision collides with own player

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#3825]
### Describe the bug?

Dynamic bone player collision collides with own player

### To Reproduce

Equip an avatar with hair dynamic bones or breasts
You'll notice that your dynamic bones are behaving abnormally and are not producing desired behavior

### Expected behavior

Dynamic player collision should only collide with other players

### Screenshots

Dynamic player collision on
![Image](https://github.com/user-attachments/assets/50ec6636-e961-419c-85d5-b87c8ba2d66e)

Dynamic player collision off
![Image](https://github.com/user-attachments/assets/71d17938-64c9-41bb-8918-8cd794665ead)

### Resonite Version Number

Beta 2025.2.25.1316

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop (But I think platform is irrelevant)

### Log Files

Log file shows me logging in opening a grid space and opening up my radial menu to turn off my player collisions
[EPICEASTON197 - 2025.2.25.1316 - 2025-02-25 20_25_33.log](https://github.com/user-attachments/files/18975168/EPICEASTON197.-.2025.2.25.1316.-.2025-02-25.20_25_33.log)

### Reporters

@epicEaston197

**Comment by epicEaston197** [comment]
> Is this with CollideWithOwnBody off on those dynamic bones?
> 
> That option turns own body collisions off, so you might just need to disable it if you don't wan them collided.

Collide with own body is enabled in both screenshots but keeping dynamic bone player collisions on and disabling kaleidosome body doesn't fix the problem

Deduced that it is Dynamic bone player collision

**Comment by Frooxius** [comment]
Can you turn on collider visualization with the "ColliderWithOwnBody" off?

**Comment by epicEaston197** [comment]
> Can you turn on collider visualization with the "ColliderWithOwnBody" off?

![Image](https://github.com/user-attachments/assets/841784e3-d589-4575-ade9-b3120709ed97)

**Comment by Frooxius** [comment]
I see thanks! I know what the issue is now, working on it.

**Comment by Frooxius** [comment]
This should be fixed in 2025.2.26.174! You'll need to make sure that ColliderWithOwnBody is turned on!

Closing this now, if there's still issues let us know and we'll reopen. Thanks!

**Comment by epicEaston197** [comment]
> This should be fixed in 2025.2.26.174! You'll need to make sure that ColliderWithOwnBody is turned on!
> 
> Closing this now, if there's still issues let us know and we'll reopen. Thanks!

Confirmed it is now fixed thank you

**Comment by ko-tengu** [comment]
This still is happening on my avatars.

![Image](https://github.com/user-attachments/assets/2f707d0b-44ec-4598-b5ad-e28a4884fd1c)
![Image](https://github.com/user-attachments/assets/cf4fa8cf-87c7-4afe-9031-fd1c4dc01a9e)

**Comment by Frooxius** [comment]
@ko-tengu I don't understand what I'm looking for there. 

The behavior looks correct as far as I can tell - when it's on, there's collection, when it's off, there's no collisions.

**Comment by ko-tengu** [comment]
I have collide with own body off and my hands are colliding with my sleeves; i would like them to be able to collide with other players but not myself

**Comment by Frooxius** [comment]
I still don't understand. They don't seem to be colliding in the first screenshot. Isn't that the behavior you want?

**Comment by ko-tengu** [comment]
The first screen shot has universally turned off hand collision, I'm to understand it should not be colliding with myself when i tell it to not collide with myself
