### ISSUE TITLE
[Prerelease] Bhaptics vest not working

### ISSUE THREAD

**Issue by ClimberJ** [Yellow-Dog-Man/Resonite-Issues#4414]
### Describe the bug?

My bHaptics vest does not appear to work in the current prerelease. The connection to the software gets established, but there are no haptic points being generated for it. The same haptic trigger triggered the haptics in my controllers.

### To Reproduce

- Start Resonite while using a bHaptics vest
- Do something that would normally trigger haptics

### Reproduction Item/World

N/A

### Expected behavior

Haptics should be triggered

### Resonite Version Number

Beta 2025.5.20.1307

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vale Index

### Log Files

[DESKTOP-FSJ2004 - 2025.5.20.1307 - 2025-05-21 00_15_07.log](https://github.com/user-attachments/files/20357454/DESKTOP-FSJ2004.-.2025.5.20.1307.-.2025-05-21.00_15_07.log)

### Reporters

Climber

**Comment by Frooxius** [comment]
Just a note: As per the Pre-release testing reporting instructions, use the Prerelease template please. It doesn't show up properly with the label when you don't.

**Comment by ClimberJ** [comment]
Sorry, I noticed the separate label after already submitting this issue.

**Comment by Frooxius** [comment]
@ClimberJ I've pushed a new pre-release 2025.5.20.1358. Can you re-test on that one and send me log please? It has some additional debugging information.

**Comment by ClimberJ** [comment]
[DESKTOP-FSJ2004 - 2025.5.20.1358 - 2025-05-21 00_54_00.log](https://github.com/user-attachments/files/20357827/DESKTOP-FSJ2004.-.2025.5.20.1358.-.2025-05-21.00_54_00.log)

It seems to partially work now. But the haptic samplers on my back are triggering both the front and back haptic points on my vest. So the lowest left haptic sampler on my back triggers both the lowest left point on the back and the lowest left point on the front of my vest. The front ones don't trigger anything at all, except the debug visual. The debug visuals are displaying the usual expected state.

**Comment by Frooxius** [comment]
@ClimberJ I've pushed a build 2025.5.21.1095. Can you try with that one and see if the issue still persists?

**Comment by ClimberJ** [comment]
@Frooxius The issue persists in 2025.5.21.1095. Here are the logs:

[DESKTOP-FSJ2004 - 2025.5.21.1095 - 2025-05-21 20_33_16.log](https://github.com/user-attachments/files/20373702/DESKTOP-FSJ2004.-.2025.5.21.1095.-.2025-05-21.20_33_16.log)

**Comment by Frooxius** [comment]
@ClimberJ This is very strange. What exactly do the haptic point visuals look like? Can you share a screenshot?

I assume this behavior does not occur on the main build?

**Comment by ClimberJ** [comment]
@Frooxius The haptic point visuals look like they usually do. White spheres that turn blue when haptics should be triggered.
I will test on the main build and get back to you then.

**Comment by Frooxius** [comment]
@ClimberJ I meant what is their actual arrangement. Can you share a screenshot please?

**Comment by ClimberJ** [comment]
I'll share a screenshot once I am back on prerelease, I'm already downloading the main build now. Until then, I can only tell you that the haptic point look like they are in the right position.

**Comment by ClimberJ** [comment]
@Frooxius The issue does not occur on the main build. Also, here is the screenshot you asked for:

![Image](https://github.com/user-attachments/assets/72fcd8ea-f35f-49bf-a116-ecb4fe777444)

**Comment by Frooxius** [comment]
@ClimberJ I've pushed a build 2025.5.21.1180 with some additional diagnostics. 

This build will also only initialize the front of the chest, but not the back. Can you test with that one and see how it behaves please?

Also share the log from that one, it might give more insight into what's going on.

**Comment by ClimberJ** [comment]
@Frooxius Everything seems to work as expected with only the front haptic samplers. Here is the log:

[DESKTOP-FSJ2004 - 2025.5.21.1180 - 2025-05-21 21_47_28.log](https://github.com/user-attachments/files/20374538/DESKTOP-FSJ2004.-.2025.5.21.1180.-.2025-05-21.21_47_28.log)

**Comment by Frooxius** [comment]
Thank you!
