### ISSUE TITLE
[The Splittening] Use native .NET 9 process on Linux

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#4758]
### Describe the issue.

In default state, running Resonite on Linux will run the Windows version of .NET 9 with Proton. .NET 9 supports Linux natively.

### To Reproduce

Run on Linux

### Expected behavior

On Linux, we could potentially run the main process natively with .NET 9 while the renderer runs with Proton. This might improve performance on Linux.

### Resonite Version Number

N/A

### What Platforms does this occur on?

Linux

### Log Files

N/A

### Additional Context

Assigning @BlueCyro to investigate mechanisms to achieve this.

**Comment by Redd56** [comment]
NATIVE LINUX BUILD HYPE! (semi native unity still running in proton but whatever)

**Comment by Frooxius** [comment]
This isn't native Linux build. Only part of the process, but effectively it's not native as a whole and *will* require Proton to run.

**Comment by Redd56** [comment]
true but still mostly native. unity is only rendering things

**Comment by BlueCyro** [comment]
I will have access to my PC later tonight, but this should be doable.

In C# on Linux, named memory maps don't exist and so memory maps must be backed by files.

However, most modern Linux systems have `/tmp` as a filesystem that exists mounted in RAM, so memory maps can be placed there and remain in RAM.

Wine (and proton) have the main Linux filesystem exposed as a `Z:` drive, and the main system's temp folder can be accessed by just poking around for `Z:\tmp`. I've tested this by just making a quick program to relay my key presses from one process to another and got it working with Linux .NET 9 <-> Mono under Proton


One thing I'm a little fuzzy on would be stuff like visemes since those don't have a native solution on Linux.

Currently this is a non-issue as everything runs in proton (and therefore visemes work) but with the main process being native, we'd run into at least that as one of those snags. Not sure if it'd be worth it to split that into its own process as well, or if there are now native solutions that exist for Linux.

I'll look to see if there are any more sneakies hiding around like that, but otherwise this seems fairly doable with a bit of finagling.

Since we're doing a proton hybrid, the best way I can think of is some sort of bootstrap program that initially starts in proton, spawns the unity process (still in proton) and then spawns the native .NET process as wine/proton programs can spawn native Linux processes.

The tricky part would be ensuring that .NET 9 or higher is installed on the native Linux system, but a potential solution to that is compiling a self-contained version of FrooxEngine that bundles the required runtime.

Mostly thinking out loud here for myself later, but thought I'd share anyhow.

**Comment by bdunderscore** [comment]
Generally you'd want to use `/dev/shm`, not `/tmp`, as writing to `/tmp` will eventually result in disk IO (and more importantly, will result in page locking when that flush IO occurs, which would potentially cause FrooxEngine and/or unity to block until that IO completes). So, presumably, you'd access `z:\dev\shm` there.

Another technique you can also consider is writing a native linux library which exposes a wine shim: https://gitlab.winehq.org/wine/wine/-/wikis/Winelib-User's-Guide#building-winelib-dlls
The main advantage of this is it would let you access `futex()` to wake the process on the other end.

**Comment by Raidriar796** [comment]
That doesn't seem right? Assuming `/tmp` is mounted as a tmpfs, both `/tmp` and `/dev/shm` are tmpfs, why would `/tmp` result in disk writes while `/dev/shm` wouldn't?

Besides that, yes `/dev/shm` should probably be used here, since it's tmpfs by default unlike `/tmp` and `/dev/shm` is specifically for interprocess shared memory.

**Comment by bdunderscore** [comment]
Some distributions might mount `/tmp` as a tmpfs, but not all of them. As one example, WSL's Ubuntu does not mount `/tmp` as a separate filesystem. `/dev/shm`, on the other hand, is specifically intended for this purpose, and is always mounted as a tmpfs.

One thing to watch out for is that you clean up on shutdown - otherwise the memory-mapped file will continue using memory indefinitely. A common technique here is to unlink the file once both sides are connected; that way it's automatically deleted once both processes exit.

**Comment by Raidriar796** [comment]
Ah I see. In my case and Cyro's, `/tmp` is a tmpfs by default in our distros, but it is still an assumption that shouldn't be made about other distros.

**Comment by BlueCyro** [comment]
> Some distributions might mount `/tmp` as a tmpfs, but not all of them. As one example, WSL's Ubuntu does not mount `/tmp` as a separate filesystem. `/dev/shm`, on the other hand, is specifically intended for this purpose, and is always mounted as a tmpfs.
> 
> One thing to watch out for is that you clean up on shutdown - otherwise the memory-mapped file will continue using memory indefinitely. A common technique here is to unlink the file once both sides are connected; that way it's automatically deleted once both processes exit.

The interprocess library checks when the last user of the memory-mapped file is de-allocated and removes the file afterwards using an atomic user counted I implemented in lieu of some weird handling between Linux and Windows.

I was actually going to say that `/dev` isn't accessible from within proton, but it seems that it is upon further inspection. I had assumed it wasn't accessible because it wasn't listed when using `dir` from wine's command prompt nor is it listed in Resonite's file browser. However, it does appear that navigating to `Z:\dev\shm` does work even if the directory isn't listed.

In lieu of that, we probably would be using `/dev/shm` in that case.

**Comment by Baplar** [comment]
Here is what I went through to try and debug stuff with the native build

- Resonite advertises requiring the Microsoft.WindowsDesktop.App framework to run, which prevents the Linux dotnet to even try starting it
  - Removing that requirement from Resonite.runtimeconfig.json allows us to go past that first hurdle
  - If none of Resonite's libraries actually enforce that requirement, it might be possible to lift it, as leaving it could potentially bring nothing to the table even for the Windows build
- Resonite is looking for an executable name without the .exe suffix for launching Renderite.Renderer
  - Renaming, copying or symlinking Renderite.Renderer.exe to Renderer.Renderite solves this issue
- Once this is done, Resonite expects the folder Renderite.Renderer_Data to be called Renderite_Data
  - Presumably because the folder name is built by removing the file extension and appending "_Data", and by removing the exe suffix we have replaced the "exe" extension with "Renderer"
  - Renaming, copying or symlinking the folder also solves that issue
- Resonite seems to use Windows-style environment variables to resolve some paths, which may interfere with other stuff
  - `DataPath: %appdata%/../LocalLow/Yellow Dog Man Studios/Resonite` (could be set with argument `-DataPath "$HOME/.local/share/Yellow Dog Man Studios/Resonite"` for example)
  - `CachePath: %temp%/Yellow Dog Man Studios/Resonite` (could be set with argument `-CachePath "$HOME/.cache/Yellow Dog Man Studios/Resonite"` for example)
- FrooxEngine waits indefinitely for the input interface to be initialized
  - This is where I stopped my own investigation

Since then, however, klrtk managed to get to a state where stuff is actually rendered and seems somewhat playable! I’ve gotten in touch with them to try to document what they did to reach that point.

**Comment by Baplar** [comment]
Weird thought: the renderer is the process that’s gonna receive the clipboard events, by virtue of being the one with an active window that the user can interact with, right? Currently we are planning to still have the renderer run in Wine, so could *it* use WPF to import the rich clipboard data and transfer it to FrooxEngine through IPC? Because in that case, there would potentially be no need to use a cross-platform implementation on the Unity side, and potentially no need to use WPF on the FrooxEngine side. Unless it is still needed on that side to process the passed data?
I concede that doing it that way would require implementing quite a bit of logic on the Unity side to convert the clipboard data to a form that can be passed through IPC, which somewhat defeats the purpose of having the renderer be as "dumb" as possible.

**Comment by Stellanora64** [comment]
@Frooxius I found [avalonia](https://github.com/avaloniaui/avalonia) which is meant to be a cross platform successor for WPF, however it isn't a drop in replacement.

There is Avalonia XPF which is meant to be a drop in replacement, but it needs to be licensed per app per platform, quote:

> For those seeking a cross-platform WPF, we have created Avalonia XPF, enabling WPF applications to run on macOS and Linux with little to no code changes. Avalonia XPF is a commercial product and is licensed per-app, per-platform.

**Comment by jvyden** [comment]
Avalonia might not be a good fit because it seems to require a window for clipboard access:

> The Clipboard can be access through an instance of `TopLevel` or `Window`..
> ...
> The TopLevel act as the visual root, and is the base class for all top level controls, eg. `Window`.

---

It's another native library, but it looks like SDL3's clipboard functions looks like it should fit the bill, as it supports every major platform, including Linux over X11 and Wayland. At least I believe so, I haven't tested it personally but Wayland is directly mentioned.

I don't know if you'd have to initialize a window or anything to get access to these APIs but I've had good luck with SDL not requiring such things.

https://wiki.libsdl.org/SDL3/CategoryClipboard

As for C# bindings, ppy has a good set: https://github.com/ppy/SDL3-CS/

**Comment by jvyden** [comment]
Yeah, I was able to get SDL clipboard working fairly easily, at least on Windows:

<img width="639" height="241" alt="Image" src="https://github.com/user-attachments/assets/d58b8b23-627e-4998-a0d1-eaaa895798c3" />

<details>
<summary>C# example</summary>

```csharp
using SDL;

Console.WriteLine("Clipboard test!");
SDL3.SDL_Init(SDL_InitFlags.SDL_INIT_VIDEO); // doesn't spawn a window
ThrowIfSdlError();


Console.WriteLine($"Clipboard has text? {(bool)SDL3.SDL_HasClipboardText()}");
ThrowIfSdlError();

if (SDL3.SDL_HasClipboardText())
    Console.WriteLine("\tClipboard text: " + SDL3.SDL_GetClipboardText());

Console.WriteLine($"Clipboard has image/png data? {(bool)SDL3.SDL_HasClipboardData("image/png")}");
ThrowIfSdlError();

Console.WriteLine("Setting clipboard data...");
SDL3.SDL_SetClipboardText("Testy test");
ThrowIfSdlError();

Console.WriteLine($"\tClipboard text: {(bool)SDL3.SDL_HasClipboardText()}, {SDL3.SDL_GetClipboardText()}");
ThrowIfSdlError();

return;

void ThrowIfSdlError()
{
    string? error = SDL3.SDL_GetError();
    if (!string.IsNullOrEmpty(error))
        throw new Exception("SDL Init Error: " + error);
}
```
</details>

I've uploaded my example code to https://github.com/jvyden/ClipboardTest for future reference. ppy.SDL3-CS will pull in the needed natives automatically. Looks like they ship natives for the majority of platforms (android, ios, linux, macos, win, all on x86/x64/arm32/arm64) so that won't be an issue either.

**Comment by BlueCyro** [comment]
> Yeah, I was able to get SDL clipboard working fairly easily, at least on Windows:
> <img alt="Image" width="639" height="241" src="https://private-user-images.githubusercontent.com/40577357/464460891-d58b8b23-627e-4998-a0d1-eaaa895798c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIxMzI2MTUsIm5iZiI6MTc1MjEzMjMxNSwicGF0aCI6Ii80MDU3NzM1Ny80NjQ0NjA4OTEtZDU4YjhiMjMtNjI3ZS00OTk4LWEwZDEtZWFhYTg5NTc5OGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzEwVDA3MjUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNzhlOWVlZGQzMTExYmQwODExNjMxMTViZGI5NmFiOWViMmVkNGQ5NzgyNzhkYzYwMThmZTUyN2MwMDBkMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E-EH9gob8xP7dAUM64yHMWGa9T2sKfmQBUaMPd7DX_4">
> C# example
> 
> I've uploaded my example code to https://github.com/jvyden/ClipboardTest for future reference. ppy.SDL3-CS will pull in the needed natives automatically. Looks like they ship natives for the majority of platforms (android, ios, linux, macos, win, all on x86/x64/arm32/arm64) so that won't be an issue either.

I did actually test this the other night, you need a window that's focused for this to work on wayland

**Comment by jvyden** [comment]
@Frooxius, I considered this fact too, and wondered if it would be useful for other components of the engine, because SDL has a lot of handy platform abstractions, but I'm not sure how many of them apply to FrooxEngine.

One neat component I can think of is a cross-platform message box implementation that potentially could be used to signal hard crashes but that's getting off-topic.

Maybe it's worth looking at the underlying implementation of clipboards in SDL and extracting it to a new C# library instead.

---

@BlueCyro, yeah, figures. Part of me wonders if it should be handled via the renderer as-is input, but again there's issues with that in Unity.

It would be a hack, but what if you set SDL's video driver to X11? The window in Proton-land would be running under X11 which would allow the clipboard to be shared across the whole XWayland server as far as I'm aware.

The caveat would be it wouldn't work for Wine's Wayland driver but I'm not sure of any other solution since FE doesn't create a window. XDG Desktop Portals have a clipboard implementation of some kind but that also requires a serial.

**Comment by jvyden** [comment]
@Red-M QT is pretty massive in both size in complexity. It's also built with C++ which means you can't really get good interop with most languages including C#. You really want something lightweight that uses a C ABI.

SDL is pretty well self-contained and uses C ABI (and already has existing sets of bindings for C#) which is why I bring it up. As far as I know QT in C# hasn't *truly* been done, and if it has it doesn't stayed maintained for very long.

**Comment by iamgreaser** [comment]
While you're still using Unity for rendering, use whatever the heck is offered in the renderer frontend and pass it onto the FrooxEngine process. Anything else is going to be a horrible kludge that will break the moment someone breathes within a 100km radius of it.

Yes, this does means that if you decide to use the native Linux version of the Unity engine, you will only be able to copy-paste text. (That, and the scroll wheel will be backwards due to that one Unity bug - compensating for this would be much appreciated!)

What follows is mostly for reference for when you start getting rid of Unity itself.

----

Clipboards are quite a funky thing. For X11 you would do something like this:

- Use the `UTF8_STRING` target for text, and the `image/png` target for images - and yes, that will actually be a PNG image
- When pasting into your program, read from the `CLIPBOARD` selection
- When copying from your program, track the contents and claim ownership of `CLIPBOARD` and `PRIMARY`
- When the clipboard contents are too large to fit trivially, there's something you have to do but I've yet to play around with this myself - it might involve the `INCR` target?

Usually there is a clipboard manager involved and running as part of the user's desktop environment, so the contents of the clipboard can outlast the program.

I cannot vouch for Wayland as I don't use it. In the worst case, people can make use of the XWayland X11 server.

I've also yet to play around with the Win32 approach to the clipboard but that really is only a matter of time before I do mess around with it.

The simplest answer is probably going to at least eventually be:

- Use SDL3. (You'll probably end up using it for other things later.)
- Use the text API for text.
- For X11, use `image/png` for images. If you want stuff to go fast, consider setting the compression strength to as low as it can go when setting the clipboard contents.
- For Win32, try to find out what MIME types are actually used for images - check with browsers and various other things. It'll probably be `image/bmp`. Raw DIBs might be better, but the rationale for using a DIB instead of a BMP pertains to system palettes and is probably a non-issue when using direct-colour output.

**Comment by Frooxius** [comment]
@iamgreaser Like I said above, clipboard doesn't really work with Unity and it never did. We've been using a separate .NET Framework process to proxy clipboard up until now because of that reason.

This solution was janky and there were some minor issues with it, so having it in the main process actually made things simpler.

And with .NET 9 we can can use libraries that we were not able to before. We're not really going to develop a custom approach for this if good libraries are available and there's a few options.

We already have images working on Windows as well, so that's not really a concern.

We're currently looking into this library: github.com/ChurchTao/clipboard-rs which seems promising and have abstractions for multiple systems.

**Comment by uyjulian** [comment]
For SDL, to reduce binary size, it is possible to disable subsystems and backends when compiling it (e.g. only keeping the video subsystem with windows backend for clipboard support and dialog subsystem for dialog boxes). But in the case of Windows (WinNT) and Linux, unused portions of the library are swapped outside of memory so there is less need to do that on those platforms.

**Comment by OrionMoonclaw** [comment]
Looking into audio stuff, it seems like there exists an experimental [version of CSCore that has Linux support using OpenAL](https://github.com/filoe/cscore/tree/netstandard), but since FrooxEngine relies on CoreAudioAPI for enumeration and playback, that would have to be reworked.

**Comment by Frooxius** [comment]
We're not going to stay with CSCore. Our plan is to either use SDL or SoundFlow right now.

**Comment by Baplar** [comment]
The current pre-release can now be started on Linux! It only requires a few manual tricks.

_NB: All of the paths in the code snippets below assume your Steam library is setup at the default location `$HOME/.local/share/Steam`. If your setup is different, adapt the paths accordingly._

- (Optional) Make a backup of your current Proton prefix, to be able to restore your release environment
```
cd $HOME/.local/share/Steam/steamapps/compatdata/
cp -r 2519830{,-release}
```
- Switch to the prerelease beta on Steam
- Launch Resonite once from Steam to pre-heat the Proton prefix and install the .NET dependencies (it will eventually crash after installing the dependencies, this is expected)
- Edit the file `Resonite.runtimeconfig.json` to remove the WindowsDesktop framework dependency
```
cd $HOME/.local/share/Steam/steamapps/common/Resonite
unix2dos <<EOF | patch --unified --binary Resonite.runtimeconfig.json
--- Resonite.runtimeconfig.json.bak	2025-07-16 09:44:51.509893740 +0200
+++ Resonite.runtimeconfig.json	2025-07-16 12:34:45.303342913 +0200
@@ -5,10 +5,6 @@
       {
         "name": "Microsoft.NETCore.App",
         "version": "9.0.0"
-      },
-      {
-        "name": "Microsoft.WindowsDesktop.App",
-        "version": "9.0.0"
       }
     ],
     "configProperties": {
EOF
```
- To launch the game, you will need to run a command instead of using Steam
```
cd $HOME/.local/share/Steam/steamapps/common/Resonite
dotnet Resonite.dll > Logs/dotnet.log 2> Logs/dotnet.err.log
```
Doing this will run the Resonite renderer within your system-wide Wine by default. You will need to have setup dxvk and dotnetdesktop9 in order for it to work.

-----

Optionally, in addition to all the previously described steps, you can add a few more "hack-y" steps to run the renderer within your chosen Proton version.
These steps require `protontricks` to run.

- (Optional) Add dxvk to your Proton prefix for better performance
```
protontricks 2519830 dxvk
```
- In the Resonite install directory, move all of the contents of the `Renderer` folder into a `Renderite` subfolder
```
cd $HOME/.local/share/Steam/steamapps/common/Resonite/Renderer
mkdir -p Renderite
mv -b MonoBleedingEdge Renderite.Renderer* Unity* Renderite
```
- Create the modified renderer script
```
cd $HOME/.local/share/Steam/steamapps/common/Resonite/Renderer
cat > Renderite.Renderer.exe <<EOF
#!/usr/bin/env bash
cd "./Renderer/Renderite" || exit
protontricks-launch --no-term --appid 2519830 Renderite.Renderer.exe "\$@"
EOF
chmod +x Renderite.Renderer.exe
```
- Launch the game in the same way as described earlier for the non-proton version
```
cd $HOME/.local/share/Steam/steamapps/common/Resonite
dotnet Resonite.dll > Logs/dotnet.log 2> Logs/dotnet.err.log
```

**Comment by ptelder** [comment]
I'm running into a wall with the procedure described by @Baplar.

I'm on AMD & Fedora, and I'm not certain where the culprit is. It looks like the Renderite process is having some issues. Initially, it wasn't seeing any form of DX11 (DVVK or WineD3D) at all. Adding "--no-bwrap" to the protontricks-launch command got past that point, but I'm still seeing Renderite crash out. 

I've also tried "--no-runtime" with protontricks, but it didn't seem to make a difference.

Right now, I'm not seeing a clear cause for the thread coming to a halt. I'm wondering if maybe my logs deviate from someone who has a working setup?

[fedora - linux-dotnet - 2025-07-16 21_20_14.log](https://github.com/user-attachments/files/21280248/fedora.-.linux-dotnet.-.2025-07-16.21_20_14.log)
[fedora - 2025.7.16.1377 - 2025-07-16 21_20_14.log](https://github.com/user-attachments/files/21280249/fedora.-.2025.7.16.1377.-.2025-07-16.21_20_14.log)

**Comment by Stellanora64** [comment]
@ptelder you are running into https://github.com/Yellow-Dog-Man/SharpFont/issues/1

There is a work around on that issue to create a sym link that should fix it for now

**Comment by BlueCyro** [comment]
> Native seems to work with the workarounds, but I only get about 30 to 50 frames with it noticeably collapsing every 10 seconds.
> Intel i5-8600K, Radeon RX 7900 XTX, 32GB, Fedora 42

Are you running in proton or system wine? Also make sure you have at least fsync and dxvk in your prefix

**Comment by phil-flip** [comment]
> > Native seems to work with the workarounds, but I only get about 30 to 50 frames with it noticeably collapsing every 10 seconds.
> > Intel i5-8600K, Radeon RX 7900 XTX, 32GB, Fedora 42
> 
> Are you running in proton or system wine? Also make sure you have at least fsync and dxvk in your prefix

I followed the instructions above. so I'm guessing system-wine? I have to test this another time again. but the 2nd time I ran it worked fine, til the Renderer, Screen share and Wayland combo crashed Resonite and my PC :D

**Comment by ptelder** [comment]
> [@ptelder](https://github.com/ptelder) you are running into [Yellow-Dog-Man/SharpFont#1](https://github.com/Yellow-Dog-Man/SharpFont/issues/1)
> 
> There is a work around on that issue to create a sym link that should fix it for now

@Stellanora64 - I didn't think I was running into that one since I didn't have any errors loading libfreetype - I did create the link though and as far as I can tell there is no change in my logging.

I am seeing though a warning about an unresolved symbol - so the root issue is likely something similar.

**Comment by CheesecakeCG** [comment]
Here is a log for the SRanipal issue:
<details><summary>The errors from the log</summary>

```
System.DllNotFoundException: Unable to load shared library 'SRanipal' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux-x64/native/SRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux/native/SRanipal.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.5/SRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/SRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux-x64/native/libSRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux/native/libSRanipal.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.5/libSRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/libSRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux-x64/native/SRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux/native/SRanipal: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.5/SRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/SRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux-x64/native/libSRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux/native/libSRanipal: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.5/libSRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/libSRanipal: cannot open shared object file: No such file or directory

   at ViveSR.anipal.Eye.SRanipal_Eye_API.IsViveProEye()
   at ViveProEyeTrackingDriver.ShouldRegister(LaunchOptions options, InputInterface input)
   at FrooxEngine.Engine.<>c__DisplayClass348_0.<InitializeInputDrivers>b__0()
   at FrooxEngine.InputInterface.Update(Single deltaTime)
   at FrooxEngine.Engine.UpdateStep()
   at FrooxEngine.Engine.RunUpdateLoop()
22:39:55.154	Unhandled Exception:

System.DllNotFoundException: Unable to load shared library 'SRanipal' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux-x64/native/SRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux/native/SRanipal.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.5/SRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/SRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux-x64/native/libSRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux/native/libSRanipal.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.5/libSRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/libSRanipal.so: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux-x64/native/SRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux/native/SRanipal: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.5/SRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/SRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux-x64/native/libSRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/runtimes/linux/native/libSRanipal: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.5/libSRanipal: cannot open shared object file: No such file or directory
/mnt/LinuxGames/SteamLibrary/steamapps/common/Resonite/libSRanipal: cannot open shared object file: No such file or directory

   at ViveSR.anipal.Eye.SRanipal_Eye_API.IsViveProEye()
   at ViveProEyeTrackingDriver.ShouldRegister(LaunchOptions options, InputInterface input)
   at FrooxEngine.Engine.<>c__DisplayClass348_0.<InitializeInputDrivers>b__0()
   at FrooxEngine.InputInterface.Update(Single deltaTime)
   at FrooxEngine.Engine.UpdateStep()
   at FrooxEngine.Engine.RunUpdateLoop()
   at GraphicalClient.GraphicalClientRunner.UpdateLoop() in D:\Workspace\Everion\FrooxEngine\GraphicalClient\GraphicalClientRunner.cs:line 145|
```

</details> 

The full log: [O990-Wyvern - 2025.7.31.1214 - 2025-07-31 22_39_47.log](https://github.com/user-attachments/files/21540838/O990-Wyvern.-.2025.7.31.1214.-.2025-07-31.22_39_47.log)
